# -*- coding: utf-8 -*-
"""dimensionality-reduction-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_FpPw3DxymV-HyBTZ9MYRLorE7WAF77q

## Dimensionality Reduction in Practice: PCA vs t-SNE vs UMAP

### Project Summary
High-dimensional data can be difficult to interpret, visualize, and model directly. This project explores three widely used dimensionality reduction methods—PCA, t-SNE, and UMAP—and compares how each algorithm transforms the same dataset into a low-dimensional representation.

### Goals
- Apply PCA, t-SNE, and UMAP to reduce dimensionality and visualize structure in the data.
- Compare each method’s strengths and limitations, including when it performs well or poorly.
- Interpret the resulting embeddings using quantitative checks (when applicable) and qualitative visual analysis.

## Install the Required Libraries
"""

!pip install -q numpy pandas matplotlib seaborn scikit-learn umap-learn

"""## Import the librareis"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Data set
from sklearn.datasets import load_digits, load_breast_cancer

#Algorithm for Dim reduction
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import umap.umap_ as umap

# Any new imports go here

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

"""## Load the Dataset"""

# Dataset 1: Digits
digits = load_digits()
X_digits = digits.data
y_digits = digits.target

print("Digits data shape:", X_digits.shape)
print("Digits number of classes:", len(np.unique(y_digits)))

# Dataset 2: Breast Cancer
cancer = load_breast_cancer()
X_cancer = cancer.data
y_cancer = cancer.target

print("Cancer data shape:", X_cancer.shape)
print("Cancer number of classes:", len(np.unique(y_cancer)))

"""## Task 1 standardize and Initialize

###Task 1.1
**Data Standardization or normalization**
"""

# TODO: Standardize the dataset 1
scaler_digits = StandardScaler()
X_digits_std = scaler_digits.fit_transform(X_digits)


# TODO: Standardize the dataset 2
scaler_cancer = StandardScaler()
X_cancer_std = scaler_cancer.fit_transform(X_cancer)

"""### Task 1.2
**Initialize PCA for both dataset**
"""

pca_digits = PCA()
X_digits_std_pca = pca_digits.fit_transform(X_digits_std)

pca_cancer = PCA()
X_cancer_std_pca = pca_cancer.fit_transform(X_cancer_std)

"""##  Task 2:
- Visualize principle components and their variance coverage
- Find the minimum number of PCA components required to explain $\geq$ 90% variance.

### Task 2.1
**Plot the CDF of the variance covered by the principle components for both of the data set.**
"""

# TODO complete the following function
def plot_cumulative_variance_all(cum_var, title="Cumulative Variance"):
    plt.figure(figsize=(7,5))
    plt.plot(range(1, len(cum_var) + 1), cum_var, marker='o')
    plt.axhline(0.9, linestyle='--', color='red', label='90% Variance')
    plt.xlabel("Number of Principal Components")
    plt.ylabel("Cumulative Explained Variance")
    plt.title(title)
    plt.legend()
    plt.grid(True)
    plt.show()

# TODO compute the cumulative variance
cumvar_digits = np.cumsum(pca_digits.explained_variance_ratio_)
cumvar_cancer = np.cumsum(pca_cancer.explained_variance_ratio_)

plot_cumulative_variance_all(cumvar_digits, "Digits – PCA Cumulative Variance (All Components)")
plot_cumulative_variance_all(cumvar_cancer, "Cancer – PCA Cumulative Variance (All Components)")

"""###Task 2.2
**Write a function to return the minimum pca component required to explain $\geq$ 90% variance for a data set.**
"""

def get_optimal_pca_components(pca_X, threshold=0.90):
    cum_var = np.cumsum(pca_X.explained_variance_ratio_)
    return np.argmax(cum_var >= threshold) + 1

opt_digits = get_optimal_pca_components(pca_digits, threshold=0.90)
print("Digits: minimum number of PCA components for ≥ 90% variance =", opt_digits)

opt_cancer = get_optimal_pca_components(pca_cancer, threshold=0.90)
print("Cancer: minimum number of PCA components for ≥ 90% variance =", opt_cancer)

"""## Task 3: Reconstruction Error with default 2 top principle components"""

pca_digits_2 = PCA(n_components=2)
X_digits_pca2 = pca_digits_2.fit_transform(X_digits_std)              # fit the digit data
X_digits_recon = pca_digits_2.inverse_transform(X_digits_pca2)        # reconstruct from top 2 PCs
error_digits_pca = mean_squared_error(X_digits_std, X_digits_recon)   # reconstruction error

pca_cancer_2 = PCA(n_components=2)
X_cancer_pca2 = pca_cancer_2.fit_transform(X_cancer_std)              # fit the cancer data
X_cancer_recon = pca_cancer_2.inverse_transform(X_cancer_pca2)        # reconstruct from top 2 PCs
error_cancer_pca = mean_squared_error(X_cancer_std, X_cancer_recon)   # reconstruction error

print("Digits PCA (2 components) reconstruction error:", error_digits_pca)
print("Cancer PCA (2 components) reconstruction error:", error_cancer_pca)

def plot_2d(X_emb, y, title):
    plt.figure(figsize=(7,5))
    scatter = plt.scatter(X_emb[:,0], X_emb[:,1], c=y, cmap='tab10', s=15)
    plt.xlabel("Component 1")
    plt.ylabel("Component 2")
    plt.title(title)
    plt.colorbar(scatter)
    plt.grid(True)
    plt.show()
plot_2d(X_digits_pca2, y_digits, "Digits PCA 2D Projection")
plot_2d(X_cancer_pca2, y_cancer, "Cancer PCA 2D Projection")

"""## Task 4
- **Q1: Explain why classes in the Digits dataset are less separable than those in the Cancer dataset using PCA for low-dimensional (2D) embeddings?**

The Digits dataset contains many classes with complex and nonlinear variation, and several digits share similar pixel patterns, causing overlap when projected using a linear method like PCA.  
In contrast, the Cancer dataset is a binary classification problem with features that align more strongly with the class distinction, so the main directions of variance captured by PCA provide better separation in low-dimensional space.

## Task 5: Analyse the class separability of TSNE and UMAP

### Task 5.1
- **Initialize the TSNE & UMAP for both data set**
"""

# t-SNE
tsne_digits = TSNE(n_components=2, random_state=42)
X_digits_tsne = tsne_digits.fit_transform(X_digits_std)

tsne_cancer = TSNE(n_components=2, random_state=42)
X_cancer_tsne = tsne_cancer.fit_transform(X_cancer_std)

# UMAP
umap_digits = umap.UMAP(n_components=2, random_state=42)
X_digits_umap = umap_digits.fit_transform(X_digits_std)

umap_cancer = umap.UMAP(n_components=2, random_state=42)
X_cancer_umap = umap_cancer.fit_transform(X_cancer_std)

"""## Visualize each of the classes for both data set

"""

def plot_embedding(X_emb, y, title):
    plt.figure(figsize=(7,5))
    scatter = plt.scatter(X_emb[:,0], X_emb[:,1], c=y, cmap='tab10', s=15)
    plt.xlabel("Component 1")
    plt.ylabel("Component 2")
    plt.title(title)
    plt.colorbar(scatter)
    plt.grid(True)
    plt.show()

# Example for digits
plot_embedding(X_digits_tsne, y_digits, "Digits – t-SNE")
plot_embedding(X_digits_umap, y_digits, "Digits – UMAP")

# Example for cancer
plot_embedding(X_cancer_tsne, y_cancer, "Cancer – t-SNE")
plot_embedding(X_cancer_umap, y_cancer, "Cancer – UMAP")

"""### Task 5.1
- **Q1:  What do you observe about class separability in the 2D embedded space when using t-SNE and UMAP?**

Both t-SNE and UMAP show improved class separability compared to PCA.  
t-SNE forms very dense and clearly separated clusters, emphasizing local neighborhood structure, but the distances between clusters are not globally meaningful.  
UMAP also produces distinct clusters while better preserving global structure, making inter-cluster spacing more interpretable.

### Task 5.2

- **Q1: Based on your understanding which method would you use to visually explore clusters in high-dimensional data, and why?**

For visual exploration of clusters, UMAP is generally the most suitable method.  
PCA is fast and interpretable but may not separate clusters well when the data has nonlinear structure.  
t-SNE is effective at revealing local clusters, but it does not preserve global structure and inter-cluster distances can be misleading.  
UMAP balances strong local clustering with better preservation of global relationships, making it useful for exploratory visualization.
"""